arch:
  - ppc64le
os: linux
services:
  - docker
language: python
python:
  - "3.6"
before_install:
  - docker pull alpine 
install:
  - docker build -t hello-py Dockerfiles/
build:
   dockerfile: Dockerfile
script: 
  - docker run -d hello-py
  - docker ps -a
  
