arch:
  - amd64
  - ppc64le
os: linux
services:
  - docker
language: python
python:
  - "3.6"
before_install:
  - docker pull alpine 
script: 
  - docker build -t hello-py Dockerfiles/
  - docker images
  - docker run hello-py
