#!/bin/bash -e
# ----------------------------------------------------------------------------
# Package          : grafana/mimir
# Version          : mimir-2.5.0
# Source repo      : https://github.com/grafana/mimir.git
# Tested on        : UBI 8.5
# Language         : Go
# Disclaimer       : This script has been tested in root mode on given
# ==========         platform using the mentioned version of the package.
#                    
#
# ----------------------------------------------------------------------------

PACKAGE_NAME="github.com/grafana/mimir"
PACKAGE_VERSION="${1:-mimir-2.5.0}"
PACKAGE_URL="https://github.com/grafana/mimir.git"
NODE_VERSION=v18.9.0
GO_VERSION=1.18.1

 

cd /
PATH=/node-$NODE_VERSION-linux-ppc64le/bin:$PATH
yum install -y wget git make gcc-c++ && \
    wget https://nodejs.org/dist/$NODE_VERSION/node-$NODE_VERSION-linux-ppc64le.tar.gz && \
    tar -C / -xzf node-$NODE_VERSION-linux-ppc64le.tar.gz && \
    rm -rf node-$NODE_VERSION-linux-ppc64le.tar.gz && \
    npm install -g yarn

cd /
GOPATH=/go
PATH=$PATH:/usr/local/go/bin

wget https://golang.org/dl/go$GO_VERSION.linux-ppc64le.tar.gz && \
tar -C /usr/local -xzf go$GO_VERSION.linux-ppc64le.tar.gz && \
rm -rf go$GO_VERSION.linux-ppc64le.tar.gz

yum install -y git golang
go get github.com/google/go-jsonnet/cmd/jsonnet

mkdir -p $GOPATH/src/github.com/grafana/
cd $GOPATH/src/github.com/grafana/
git clone https://github.com/grafana/mimir.git
cd mimir
git checkout $PACKAGE_VERSION

go mod tidy
go test ./... -cover -v 
exit 0
